# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GUITask3' do
pod 'FBSDKCoreKit', '~> 4.7'
end

target 'GUITask3Tests' do

end

